### ISSUE TITLE
the cluster IP [IPv4]:10.96.0.1 for service kubernetes/default is not allocated; repairing

### ISSUE THREAD

**Issue by jason0392** [cby-chen/Kubernetes#18]
`E0831 15:09:51.692706   29299 controller.go:152] Unable to remove old endpoints from kubernetes service: StorageError: key not found, Code: 1, Key: /registry/masterleases/192.168.0.201, ResourceVersion: 0, AdditionalErrorMsg:
E0831 15:09:51.725003   29299 repair.go:240] the cluster IP [IPv4]:10.96.0.1 for service kubernetes/default is not allocated; repairing
E0831 15:09:51.732993   29299 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0x5, desc:"etcdserver: requested lease not found"}: etcdserver: requested lease not found
E0831 15:09:51.733622   29299 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kubernetes.17105c571d68038c", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Service", Namespace:"default", Name:"kubernetes", UID:"b9bb6e28-02ce-4be8-9fb4-8053fbf428f4", APIVersion:"v1", ResourceVersion:"3404", FieldPath:""}, Reason:"ClusterIPNotAllocated", Message:"Cluster IP [IPv4]:10.96.0.1 is not allocated; repairing", Source:v1.EventSource{Component:"ipallocator-repair-controller", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc0bbe02feb364d8c, ext:3117973040, loc:(*time.Location)(0x78a5340)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc0bbe02feb364d8c, ext:3117973040, loc:(*time.Location)(0x78a5340)}}, Count:1, Type:"Warning", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'etcdserver: requested lease not found' (will not retry!)
E0831 15:09:51.742897   29299 repair.go:301] the cluster IP 10.96.0.1 may have leaked: flagging for later clean up
E0831 15:09:52.081319   29299 repair.go:240] the cluster IP [IPv4]:10.96.0.1 for service kubernetes/default is not allocated; repairing
F0831 15:09:52.082530   29299 controller.go:161] Unable to perform initial IP allocation check: Operation cannot be fulfilled on serviceipallocations "": the provided resource version does not match
goroutine 3304 [running]:
`
您好，启动apiserver以后，出现了active(running)，但是很快会重启，日志中显示cluster IP 无法被分配，我尝试修改掉之前的cluster IP（10.96.0.1），但是无法修改成功，我是把证书重新生成，hosts文件中改成了10.0.0.1 但是，启动以后
执行kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   8d
依然是10.96.0.1，请问这个问题应该怎么解决？
十分感谢！！

**Comment by mrzhu147** [comment]
the cluster IP [IPv4]:10.96.0.2  设置成10.96.0.2 试试
